SFDC/VFP-Part-2/src/objects/Custom_Product__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quatity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Quatity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_per_item__c</fullName>
        <label>Price per item</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Custom Product</label>
    <nameField>
        <label>Custom Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/VFP-Part-2/src/objects/Purchase_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Custom Product</label>
        <referenceTo>Custom_Product__c</referenceTo>
        <relationshipLabel>PurchaseLineItems</relationshipLabel>
        <relationshipName>PurchaseLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_per_item__c</fullName>
        <label>Price per item</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>PurchaseLineItems</relationshipLabel>
        <relationshipName>PurchaseLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Line Item</label>
    <nameField>
        <label>Purchase Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/VFP-Part-2/src/objects/Purchase_Order__c.object
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/VFP-Part-2/src/classes/OnlineShoppingController.cls
public class OnlineShoppingController {
    public List<Custom_Product__c> productList {set ;get;}
    public string selectedCategory {set ;get;}
    public List<Purchase_Line_Item__c> PurchaseLineItemList {set ;get ;}
    public String productID {get ;set ;}
    public String orderID {get ;set ;}
    public List<Id> numberOfLineItems {get ;set;}
    public Boolean isAllCorrect{get ; set;}
    
    public OnlineShoppingController() {
        isAllCorrect = true;
        numberOfLineItems = new List<Id>();
    }
    
    public List<SelectOption> getCategory() {
        
        List<SelectOption> category = new List<SelectOption>();
       
        for(Custom_Product__c product : [select category__c from Custom_Product__c] ) {
            category.add(new SelectOption(product.category__c,product.category__c));
        }
        return category;
    }
    
    public PageReference getProducts() {
        productList = [select Name,Price_Per_Item__c from Custom_Product__c where category__c =: selectedCategory];
        return null;
    }
    
    public PageReference addToCart() {
        isAllCorrect = true;
        Integer index = 0;
        Custom_Product__c prdct = [select Name,Price_Per_Item__c from Custom_Product__c where Id =:productID];
        Purchase_Line_Item__c ordrLine = new Purchase_Line_Item__c();
        ordrLine.Custom_Product__c = productID;
        ordrLine.Price_per_item__c = prdct.Price_per_item__c;
        ordrLine.Quantity__c = 0;
        String orderId = Database.insert(ordrLine).getId();
        ordrLine.Id = orderId;
        if(PurchaseLineItemList == null) {
            PurchaseLineItemList = new List<Purchase_Line_Item__c>();
        }
        for(Custom_Product__c prdct1 : productList) {
            if(prdct1.Id == prdct.Id) 
                break;
            index++;
        }
        productList.remove(index);
        PurchaseLineItemList.add(ordrLine);
 		return null;       
    }
    
    public PageReference remove() {
       	System.debug('orderID' + orderID);
        Integer index = 0;
        for(Purchase_Line_Item__c item : PurchaseLineItemList ) {
            if(item.id == orderID) {
                Purchase_Line_Item__c item1= PurchaseLineItemList.remove(index);
                System.debug('item1' + item1);
                productList.add([select Name,Price_Per_Item__c from Custom_Product__c where Id =:item1.Custom_Product__c]);
       			Database.delete(orderID);
                break;
            }
                
                index++;
        }
        index = 0;
        for(Id idFromList : numberOfLineItems) {
           	   if(idFromList == orderID) {
                   break;
            	}
            index++;
       	    } 
        numberOfLineItems.remove(index);
        if(numberOfLineItems.size() == PurchaseLineItemList.size()) {
            isAllCorrect = false;
        }
        if(numberOfLineItems.size() == 0) {
            isAllCorrect = true;
        }
        System.debug('numberOfLineItems.size() == PurchaseLineItemList.size()  '+numberOfLineItems.size() +' '+ PurchaseLineItemList.size());
        return null;
    }
    
    public PageReference addToOrder() {
        Purchase_Order__c ordr = new Purchase_Order__c();
        String orderId = Database.insert(ordr).getId();
        ordr.Id = orderId;
        for(Purchase_Line_Item__c lineItem : PurchaseLineItemList) {
            lineItem.Purchase_Order__c = orderId;
        }
        upsert PurchaseLineItemList; 
        return null;
    }
    
    public PageReference checkQuantity() {
        Integer index = 0;
        for(Purchase_Line_Item__c item : PurchaseLineItemList ) {
            if(item.id == orderID) {
                break;
            }
            index++;
        }
        Purchase_Line_Item__c item = PurchaseLineItemList[index];
        Custom_Product__c prdct = [select 	Available_Quatity__c from Custom_Product__c where id =: item.Custom_Product__c];
        if(prdct.Available_Quatity__c < item.Quantity__c) {
            remove();
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Sorry Quantity is not as your expectation! you can only order  '+prdct.Available_Quatity__c +' items'));
        }
        Boolean isAvail = false;
        if(numberOfLineItems.size() == 0) {
             numberOfLineItems.add(orderID);
        }
        else {
           for(Id idFromList : numberOfLineItems) {
           	   if(idFromList == orderID) {
                   isAvail=true;
                	break;
            	}
       	    } 
            if(isAvail == false) {
                numberOfLineItems.add(orderId);
            }
        }
        if(numberOfLineItems.size() == PurchaseLineItemList.size()) {
            isAllCorrect = false;
        }
        return null;
    }
}