SFDC/Trigger/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/Trigger/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students_Class</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/ApexLanguage/src/classes/Class1.cls
public class Class1 {
public static List<Student__c> getStudentList(String classId)
 {
     return [SELECT Name From Student__c where Class__r.Id =: classId];
 }
    
  public static Map<Class__c,List<Student__c>> getAllClassesWithStudentList()
  {
      Map<Class__c,List<Student__c>> m1 = new Map<Class__c,List<Student__c>>();
      for(Class__c cls : [SELECT Name FROM Class__c])
      {
          m1.put(cls, [SELECT Name From Student__c where Class__r.Id =: cls.Id]);
      }
      return m1;
  }
}