SFDC/Trigger/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/Trigger/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students_Class</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/Test Classes/src/classes/TestNotAllowInsertStudent.cls
@isTest
public class TestNotAllowInsertStudent {
@isTest
    public static void test11()
    {   
        Class__c cls = new Class__c();
        cls.Name__c ='tempClass';
        cls.MaxSize__c =1;
        insert cls;
        
        Student__c std = new Student__c();
        std.Last_Name__c = 'xyz';
        std.Email__c = 'xyz123@hfh.com';
        
        Student__c std1 = new Student__c();
        std1.Last_Name__c = 'xyz1';
        std1.Email__c = 'xy1z123@hfh.com';
        
        std.Class__c = cls.id;
        std1.Class__c = cls.id;
 
        insert std;
       
        
        Test.startTest();
        Database.SaveResult svrslt = Database.insert(std1);
        Test.stopTest();
        System.assert(!svrslt.isSuccess());
        System.assert(svrslt.getErrors().size() > 0);
        System.assertEquals('No more seat in selected class', svrslt.getErrors()[0].getMessage());

    }
}