SFDC/Trigger/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/Trigger/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students_Class</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/Java Script Use/src/classes/DeleteStudentsController.cls
public class DeleteStudentsController {
    public List<Student__c> studentList {set ; get;}
    Set<ID> idSet{set;get;}
    public Integer size{set ; get;}
    public DeleteStudentsController(ApexPages.StandardSetController controller) {
        if(idSet == null) {
            idSet = new Set<Id>();
        }
        List<Student__c> stdList = controller.getSelected();
        for(Student__c std : stdList) {
            idSet.add(std.ID);
        }
        size=0;
        size = stdList.size();
        studentList = [select ID,Name,Class__C from Student__c where ID IN : idSet];
    }
    public void deleteAll() {
        Database.delete(studentList);
    }
    
    public void showMessage() {
     System.debug('sfksjhf');  
     ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, 'No record selected'));
   
    }
}