SFDC/Trigger/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <picklist>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/VFP-Part-1/src/classes/ClassManageController.cls
public class ClassManageController {
    
    public String idOfActionRecord {get;set;}
    public boolean isEditor {get; set;} 
    public Class__c actionRecord { get; private set; }
    
    
    public String thisClass {get; set;}
   
    public ClassManageController(ApexPages.StandardController controller) { }
    
    public List<Class__C> getRecords() 
    { 
        String queryString = 'SELECT Id, Name, fee__c, board__c FROM Class__c ';
        return Database.query(queryString);
    }
    
    public void saveChanges() {  
        isEditor = false;
        update actionRecord;  
    }  
    
    public void deleteRecord() { 
        actionRecord = [SELECT id,Name,fee__C FROM Class__c WHERE id = :idOfActionRecord];
        delete actionRecord;
    }  
   
    public void getFieldToEdit() { 
        actionRecord = [SELECT id, Name, fee__c,board__C FROM Class__c WHERE id = :idOfActionRecord];
        isEditor = true;    
    }    
}